# Generated by Django 5.0.2 on 2024-02-27 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', 'populate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='api.course'),
        ),
    ]
