# Generated by Django 5.0.2 on 2024-03-05 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='group_size',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='project',
            name='max_score',
            field=models.PositiveSmallIntegerField(default=100),
        ),
    ]
