# Generated by Django 5.0.2 on 2024-03-06 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_project_checks_extracheck_structurecheck_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='structure_checks_passed',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ExtraChecksResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passed', models.BooleanField(default=False)),
                ('extra_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='api.extracheck')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_checks_results', to='api.submission')),
            ],
        ),
    ]
