# Generated by Django 5.0.2 on 2024-03-12 21:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_submission_structure_checks_passed_extrachecksresult"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="locked_groups",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="project",
            name="max_score",
            field=models.PositiveSmallIntegerField(default=20),
        ),
        migrations.AlterField(
            model_name="project",
            name="start_date",
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="submission",
            name="submission_number",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
