# Generated by Django 5.0.2 on 2024-03-12 20:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_alter_project_max_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="locked_groups",
            field=models.BooleanField(default=False),
        ),
    ]
