# Generated by Django 5.0.2 on 2024-03-13 06:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_project_locked_groups_alter_project_start_date_and_more"),
        ("api", "0006_project_score_visible_alter_project_start_date_and_more"),
    ]

    operations = []
