# Generated by Django 5.0.3 on 2024-04-04 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_add_extra_checks'),
        ('api', '0008_course_faculty'),
    ]

    operations = [
    ]
