# Generated by Django 5.0.3 on 2024-04-05 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_merge_0008_add_extra_checks_0008_course_faculty"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="errortemplate",
            new_name="ErrorTemplates",
        ),
        migrations.RenameField(
            model_name="extracheck",
            old_name="docker_image_id",
            new_name="docker_image",
        ),
        migrations.AlterField(
            model_name="dockerimage",
            name="custom",
            field=models.BooleanField(default=True),
        ),
    ]
