# Generated by Django 5.0.4 on 2024-04-09 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_revise_extra_checks'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_key', models.CharField(max_length=256)),
            ],
        ),
        migrations.AlterField(
            model_name='extrachecksresult',
            name='error_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='extra_checks_results', to='api.errortemplate'),
        ),
        migrations.DeleteModel(
            name='ErrorTemplates',
        ),
    ]
