# Generated by Django 5.0.4 on 2024-04-09 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('api', '0013_student_is_active'), ('api', '0014_assistant_is_active_teacher_is_active')]

    dependencies = [
        ('api', '0012_errortemplate_alter_extrachecksresult_error_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='assistant',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
