# Generated by Django 5.0.4 on 2024-04-11 13:57

import api.logic.get_file_path
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_student_is_active_squashed_0014_assistant_is_active_teacher_is_active'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(blank=False, choices=[('QUEUED', 'submission.state.queued'), ('RUNNING', 'submission.state.running'), (
                    'SUCCESS', 'submission.state.success'), ('FAILED', 'submission.state.failed')], default='QUEUED', max_length=256, null=False)),
                ('error_message', models.CharField(blank=True, choices=[('BLOCKED_EXTENSION', 'submission.error.blockedextension'), ('OBLIGATED_EXTENSION_NOT_FOUND', 'submission.error.obligatedextensionnotfound'), ('OBLIGATED_DIRECTORY_NOT_FOUND', 'submission.error.obligateddirectorynotfound'), ('UNASKED_DIRECTORY', 'submission.error.unaskeddirectory'), (
                    'TIMELIMIT', 'submission.error.timelimit'), ('MEMORYLIMIT', 'submission.error.memorylimit'), ('RUNTIMEERROR', 'submission.error.runtimeerror'), ('OUTPUTLIMIT', 'submission.error.outputlimit'), ('INTERNALERROR', 'submission.error.internalerror'), ('UNKNOWN', 'submission.error.unknown')], max_length=256, null=True)),
                ('is_valid', models.BooleanField(default=True)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE,
                 related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.RemoveField(
            model_name='extrachecksresult',
            name='error_message',
        ),
        migrations.RemoveField(
            model_name='extrachecksresult',
            name='extra_check',
        ),
        migrations.RemoveField(
            model_name='extrachecksresult',
            name='submission',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='structure_checks_passed',
        ),
        migrations.CreateModel(
            name='ExtraCheckResult',
            fields=[
                ('checkresult_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE,
                 parent_link=True, primary_key=True, serialize=False, to='api.checkresult')),
                ('log_file', models.FileField(max_length=256, null=True,
                 upload_to=api.logic.get_file_path.get_extra_check_log_file_path)),
                ('extra_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='api.extracheck')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('api.checkresult',),
        ),
        migrations.CreateModel(
            name='StructureCheckResult',
            fields=[
                ('checkresult_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE,
                 parent_link=True, primary_key=True, serialize=False, to='api.checkresult')),
                ('structure_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='results', to='api.structurecheck')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('api.checkresult',),
        ),
        migrations.AddField(
            model_name='checkresult',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='structure_checks_results', to='api.submission'),
        ),
        migrations.DeleteModel(
            name='ErrorTemplate',
        ),
        migrations.DeleteModel(
            name='ExtraChecksResult',
        ),
    ]
