# Generated by Django 5.0.4 on 2024-04-27 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_merge_20240416_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='invite_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
