# Generated by Django 5.0.4 on 2024-04-27 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_merge_20240416_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='structurecheck',
            name='path',
            field=models.CharField(default='.', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='structurecheck',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
