# Generated by Django 5.0.4 on 2024-04-29 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_merge_20240416_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='invitation_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='invitation_link_expires',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='private_course',
            field=models.BooleanField(default=False),
        ),
    ]
