# Generated by Django 5.0.4 on 2024-04-27 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_structurecheck_path_alter_structurecheck_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='dockerimage',
            name='state',
            field=models.CharField(choices=[('QUEUED', 'dockerimage.state.queued'), ('BUILDING', 'dockerimage.state.building'), ('READY', 'dockerimage.state.eady'), ('ERROR', 'dockerimage.state.error')], default='QUEUED', max_length=256),
        ),
    ]
