# Generated by Django 5.0.4 on 2024-04-28 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_dockerimage_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extracheck',
            name='timeout',
        ),
        migrations.AddField(
            model_name='extracheck',
            name='memory_limit',
            field=models.PositiveSmallIntegerField(default=128),
        ),
        migrations.AddField(
            model_name='extracheck',
            name='name',
            field=models.CharField(default='tmp', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='extracheck',
            name='time_limit',
            field=models.PositiveSmallIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='checkresult',
            name='error_message',
            field=models.CharField(blank=True, choices=[('BLOCKED_EXTENSION', 'submission.error.blockedextension'), ('OBLIGATED_EXTENSION_NOT_FOUND', 'submission.error.obligatedextensionnotfound'), ('OBLIGATED_DIRECTORY_NOT_FOUND', 'submission.error.obligateddirectorynotfound'), ('UNASKED_DIRECTORY', 'submission.error.unaskeddirectory'), ('DOCKER_IMAGE_ERROR', 'submission.error.dockerimageerror'), ('TIMELIMIT', 'submission.error.timelimit'), ('MEMORYLIMIT', 'submission.error.memorylimit'), ('RUNTIMEERROR', 'submission.error.runtimeerror'), ('OUTPUTLIMIT', 'submission.error.outputlimit'), ('INTERNALERROR', 'submission.error.internalerror'), ('UNKNOWN', 'submission.error.unknown')], max_length=256, null=True),
        ),
    ]
