# Generated by Django 5.0.4 on 2024-05-02 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_remove_extracheck_timeout_extracheck_memory_limit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='structurecheck',
            name='name',
        ),
        migrations.AlterField(
            model_name='checkresult',
            name='error_message',
            field=models.CharField(blank=True, choices=[('BLOCKED_EXTENSION', 'submission.error.blockedextension'), ('OBLIGATED_EXTENSION_NOT_FOUND', 'submission.error.obligatedextensionnotfound'), ('OBLIGATED_DIRECTORY_NOT_FOUND', 'submission.error.obligateddirectorynotfound'), ('UNASKED_DIRECTORY', 'submission.error.unaskeddirectory'), ('DOCKER_IMAGE_ERROR', 'submission.error.dockerimageerror'), ('TIMELIMIT', 'submission.error.timelimit'), ('MEMORYLIMIT', 'submission.error.memorylimit'), ('RUNTIMEERROR', 'submission.error.runtimeerror'), ('UNKNOWN', 'submission.error.unknown')], max_length=256, null=True),
        ),
    ]
