# Generated by Django 5.0.4 on 2024-05-02 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_course_invitation_link_and_more'),
        ('api', '0021_remove_structurecheck_name_and_more'),
    ]

    operations = [
    ]
