# Generated by Django 5.0.4 on 2024-05-05 15:41

import api.logic.get_file_path
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_merge_20240502_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='zip',
            field=models.FileField(blank=True, max_length=265, null=True, upload_to=api.logic.get_file_path.get_submission_file_path),
        ),
        migrations.AlterField(
            model_name='checkresult',
            name='error_message',
            field=models.CharField(blank=True, choices=[('BLOCKED_EXTENSION', 'submission.error.blockedextension'), ('OBLIGATED_EXTENSION_NOT_FOUND', 'submission.error.obligatedextensionnotfound'), ('FILE_DIR_NOT_FOUND', 'submission.error.filedirnotfound'), ('DOCKER_IMAGE_ERROR', 'submission.error.dockerimageerror'), ('TIME_LIMIT', 'submission.error.timelimit'), ('MEMORY_LIMIT', 'submission.error.memorylimit'), ('CHECK_ERROR', 'submission.error.checkerror'), ('RUNTIME_ERROR', 'submission.error.runtimeerror'), ('UNKNOWN', 'submission.error.unknown'), ('FAILED_STRUCTURE_CHECK', 'submission.error.failedstructurecheck')], max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='checkresult',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dockerimage',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='extracheck',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='fileextension',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='group',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='structurecheck',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='submission',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='SubmissionFile',
        ),
    ]
