# Generated by Django 5.0.4 on 2024-05-03 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_feedback'),
        ('api', '0022_merge_20240502_1552'),
    ]

    operations = [
    ]
