# Generated by Django 5.0.4 on 2024-05-11 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_submission_zip_alter_checkresult_error_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dockerimage',
            name='state',
            field=models.CharField(choices=[('QUEUED', 'dockerimage.state.queued'), ('BUILDING', 'dockerimage.state.building'), ('READY', 'dockerimage.state.ready'), ('ERROR', 'dockerimage.state.error')], default='QUEUED', max_length=256),
        ),
    ]
