# Generated by Django 5.0.4 on 2024-05-07 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_feedback'),
        ('api', '0023_submission_zip_alter_checkresult_error_message_and_more'),
    ]

    operations = [
    ]
