# Generated by Django 5.0.4 on 2024-05-13 21:33

from api.logic.get_file_path import get_extra_check_artifact_file_path
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_dockerimage_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='extracheckresult',
            name='artifact',
            field=models.FileField(max_length=256, null=True, upload_to=get_extra_check_artifact_file_path),
        ),
        migrations.AddField(
            model_name='extracheck',
            name='show_artifact',
            field=models.BooleanField(default=True),
        ),
    ]
