# Generated by Django 5.0.4 on 2024-05-18 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_merge_20240507_1230'),
        ('api', '0025_extracheckresult_artifact'),
    ]

    operations = [
    ]
