from .admin import *
from .assistant import *
from .course import *
from .checks import *
from .student import *
from .teacher import *
from .submission import *
from .project import *
from .group import *
