# Generated by Django 5.0.2 on 2024-03-05 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=12, unique=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('last_enrolled', models.IntegerField(default=1, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('faculties', models.ManyToManyField(blank=True, related_name='users', to='authentication.faculty')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
