# Generated by Django 5.0.2 on 2024-02-24 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('create_time', models.DateTimeField(auto_created=True)),
                ('last_login', models.DateTimeField(blank=True, null=True,
                 verbose_name='last login')),
                ('id', models.CharField(max_length=12, primary_key=True,
                 serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('faculty', models.CharField(max_length=50, null=True)),
                ('last_enrolled', models.IntegerField(default=1, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
