# Generated by Django 5.0.2 on 2024-02-29 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='faculty',
        ),
        migrations.AddField(
            model_name='user',
            name='faculties',
            field=models.ManyToManyField(blank=True, related_name='users', to='authentication.faculty'),
        ),
    ]
