# Generated by Django 5.0.2 on 2024-02-26 20:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True,
                 serialize=False)),
                ('user', models.ForeignKey(null=True,
                 on_delete=django.db.models.deletion.DO_NOTHING,
                 related_name='faculties',
                 to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
