# Generated by Django 5.0.3 on 2024-04-03 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faculty',
            old_name='name',
            new_name='id',
        ),
        migrations.AddField(
            model_name='faculty',
            name='description',
            field=models.CharField(default='faculty', max_length=50),
        ),
    ]
