# Generated by Django 5.0.2 on 2024-03-04 15:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0002_remove_faculty_user_remove_user_faculty_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="create_time",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
