# Generated by Django 5.0.2 on 2024-02-27 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_faculty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='faculty',
        ),
        migrations.AddField(
            model_name='user',
            name='faculty',
            field=models.ManyToManyField(null=True, related_name='faculties', to='authentication.faculty'),
        ),
    ]
