# Generated by Django 5.0.2 on 2024-02-27 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_user_faculty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='faculty',
            field=models.ManyToManyField(blank=True, related_name='faculties', to='authentication.faculty'),
        ),
    ]
