<script setup lang="ts">
import Calendar from 'primevue/calendar';
import BaseLayout from '@/components/layout/BaseLayout.vue';
import Title from '@/components/layout/Title.vue';
import { reactive, computed } from 'vue';
import { useRouter } from 'vue-router';
import { useI18n } from 'vue-i18n';
import { useAuthStore } from '@/store/authentication.store.ts';
import { storeToRefs } from 'pinia';
import InputText from 'primevue/inputtext';
import Textarea from 'primevue/textarea';
import Button from 'primevue/button';
import { Course } from '@/types/Course';
import { useCourses } from '@/composables/services/courses.service';
import { required, helpers } from '@vuelidate/validators';
import { useVuelidate } from '@vuelidate/core';
import ErrorMessage from '@/components/forms/ErrorMessage.vue';
import { User } from '@/types/users/User.ts';

/* Composable injections */
const { t } = useI18n();
const { push } = useRouter();
const { user } = storeToRefs(useAuthStore());

/* Service injection */
const { createCourse } = useCourses();

/* Form content */
const form = reactive({
    name: '',
    description: '',
    year: user.value !== null ? new Date(User.getAcademicYear(new Date()), 0, 1) : new Date(),
});

// Define validation rules for each form field
const rules = computed(() => {
    return {
        name: { required: helpers.withMessage(t('validations.required'), required) },
        year: { required: helpers.withMessage(t('validations.required'), required) },
    };
});

// useVuelidate function to perform form validation
const v$ = useVuelidate(rules, form);

const submitCourse = async (): Promise<void> => {
    // Validate the form
    const result = await v$.value.$validate();

    // Only submit the form if the validation was successful
    if (result) {
        // Pass the course data to the service
        await createCourse(
            new Course(
                '', // ID not needed for creation, will be generated by the backend
                form.name,
                form.description,
                form.year.getFullYear(),
            ),
        );

        // Redirect to the dashboard overview
        push({ name: 'dashboard' });
    }
};
</script>

<template>
    <BaseLayout>
        <div class="grid fadein">
            <div class="col-12 md:col-6">
                <!-- Create course heading -->
                <Title class="mb-6">{{ t('views.courses.create') }}</Title>

                <!-- Course form -->
                <form @submit.prevent="submitCourse">
                    <!-- Course name -->
                    <div class="mb-4">
                        <label for="courseName">{{ t('views.courses.name') }}</label>
                        <InputText id="courseName" v-model="form.name" />
                        <ErrorMessage :field="v$.name" />
                    </div>

                    <!-- Course description -->
                    <div class="mb-4">
                        <label for="courseDescription">{{ t('views.courses.description') }}</label>
                        <Textarea id="courseDescription" v-model="form.description" autoResize rows="5" cols="30" />
                    </div>

                    <!-- Course academic year -->
                    <div class="mb-4">
                        <label for="courseYear">{{ t('views.courses.year') }}</label>
                        <Calendar id="courseYear" v-model="form.year" view="year" dateFormat="yy" showIcon>
                            <template #footer>
                                <div style="text-align: center">
                                    {{ form.year.getFullYear() }} - {{ form.year.getFullYear() + 1 }}
                                </div>
                            </template>
                        </Calendar>
                        <ErrorMessage :field="v$.year" />
                    </div>

                    <!-- Submit button -->
                    <div class="flex justify-end">
                        <Button
                            :label="t('views.courses.create')"
                            type="submit"
                            icon="pi pi-check"
                            iconPos="right"
                            rounded
                        />
                    </div>
                </form>
            </div>
        </div>
    </BaseLayout>
</template>

<style scoped>
/* Flex column layout for label and input */
.mb-4 {
    display: flex;
    flex-direction: column;
}

/* Add margin between label and input */
label {
    margin-bottom: 0.5rem;
}
</style>
