<script setup lang="ts">
import Calendar from 'primevue/calendar';
import BaseLayout from '@/components/layout/BaseLayout.vue';
import Title from '@/components/layout/Title.vue';
import { ref } from 'vue';
import { useRouter } from 'vue-router';
import { useI18n } from 'vue-i18n';
import InputText from 'primevue/inputtext';
import Textarea from 'primevue/textarea';
import Button from 'primevue/button';
import { Course } from '@/types/Course';
import { useCourses } from '@/composables/services/courses.service';

/* Composable injections */
const { t } = useI18n();
const { push } = useRouter();

/* Service injection */
const { createCourse } = useCourses();

const courseName = ref<string>('');
const courseDescription = ref<string>('');
const courseYear = ref<Date>(new Date());

const submitCourse = async (): Promise<void> => {
    // Pass the course data to the service
    await createCourse(
        new Course(
            '', // ID not needed for creation, will be generated by the backend
            courseName.value,
            courseDescription.value,
            courseYear.value.getFullYear(),
        ),
    );

    // Redirect to the dashboard overview
    push({ name: 'dashboard' });
};
</script>

<template>
    <BaseLayout>
        <div class="grid fadein">
            <div class="col-12 md:col-6">
                <!-- Create course heading -->
                <Title class="mb-6">{{ t('views.courses.create') }}</Title>

                <!-- Course form -->
                <form @submit.prevent="submitCourse">
                    <!-- Course name -->
                    <div class="mb-4">
                        <label for="courseName">{{ t('views.courses.name') }}</label>
                        <InputText id="courseName" v-model="courseName" required />
                    </div>

                    <!-- Course description -->
                    <div class="mb-4">
                        <label for="courseDescription">{{ t('views.courses.description') }}</label>
                        <Textarea id="courseDescription" v-model="courseDescription" autoResize rows="5" cols="30" />
                    </div>

                    <!-- Course academic year -->
                    <div class="mb-4">
                        <label for="courseYear">{{ t('views.courses.year') }}</label>
                        <Calendar id="courseYear" v-model="courseYear" view="year" dateFormat="yy" required />
                    </div>

                    <!-- Submit button -->
                    <div class="flex justify-end">
                        <Button :label="t('views.courses.create')" type="submit" icon="pi pi-check" iconPos="right" rounded />
                    </div>
                </form>
            </div>
        </div>
    </BaseLayout>
</template>

<style scoped>
/* Flex column layout for label and input */
.mb-4 {
    display: flex;
    flex-direction: column;
}

/* Add margin between label and input */
label {
    margin-bottom: 0.5rem;
}
</style>
