version: "3.9"

############################# NETWORKS

networks:
  selab_network:
    name: selab_network
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.91.0/24

############################# EXTENSIONS

x-common-keys-selab: &common-keys-selab
  networks:
    - selab_network
  security_opt:
    - no-new-privileges:true
  restart: unless-stopped
  environment:
    TZ: $TZ
    PUID: $PUID
    PGID: $PGID
  env_file:
    - .env
  dns:
    - 1.1.1.1
    - 4.4.4.4
    - 8.8.8.8

############################# SERVICES

services:
  nginx:
    <<: *common-keys-selab
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - ${DATA_DIR}/nginx/nginx.dev.conf:/etc/nginx/nginx.conf:ro
      - ${SSL_DIR}:/etc/nginx/ssl:ro
    depends_on:
      - backend
      - frontend

  backend:
    <<: *common-keys-selab
    build:
      context: $BACKEND_DIR
      dockerfile: Dockerfile
    command: sh -c "./setup.sh; python manage.py runsslserver 0.0.0.0:8000"
    volumes:
      - ${BACKEND_DIR}:/code

  # TODO: Is this an entire different container worthy?
  celery:
    <<: *common-keys-selab
    build:
      context: $BACKEND_DIR
      dockerfile: Dockerfile
    command: sh -c "./setup.sh && celery -A ypovoli worker -l DEBUG"
    volumes:
      - ${BACKEND_DIR}:/code
    depends_on:
      - backend
      - redis

  frontend:
    <<: *common-keys-selab
    build:
      context: $FRONTEND_DIR
      dockerfile: Dockerfile.dev
    command: sh -c "npm install && npm run host"
    volumes:
      - ${FRONTEND_DIR}:/app
    depends_on:
      - backend

  redis:
    <<: *common-keys-selab
    image: redis:latest
    expose:
      - $REDIS_PORT
    entrypoint: redis-server --appendonly yes --maxmemory 512mb --maxmemory-policy allkeys-lru
    volumes:
      - ${DATA_DIR}/redis:/data
