version: "3.9"

############################# NETWORKS

networks:
  selab_network_prod:
    name: selab_network_prod
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.90.0/24

############################# EXTENSIONS

x-common-keys-selab: &common-keys-selab
  networks:
    - selab_network_prod
  security_opt:
    - no-new-privileges:true
  restart: unless-stopped
  environment:
    TZ: $TZ
    PUID: $PUID
    PGID: $PGID
  env_file:
    - .env
  dns:
    - 1.1.1.1
    - 4.4.4.4
    - 8.8.8.8

############################# SERVICES

services:
  nginx:
    <<: *common-keys-selab
    image: nginx:alpine-slim
    container_name: nginx_prod
    ports:
      - 80:80
      - 443:443
    volumes:
      - ${DATA_DIR}/nginx/nginx.prod.conf:/etc/nginx/nginx.conf:ro
      - ${SSL_DIR}:/etc/nginx/ssl:ro
    depends_on:
      - backend
      - frontend

  postgres:
    <<: *common-keys-selab
    image: postgres:15.2
    container_name: postgres_prod
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    volumes:
      - ${DATA_DIR}/postgres:/var/lib/postgresql/data

  backend:
    <<: *common-keys-selab
    container_name: backend_prod
    build:
      context: $BACKEND_DIR
      dockerfile: Dockerfile.prod
    command: sh -c "./setup.sh && gunicorn --config gunicorn_config.py ypovoli.wsgi:application"
    depends_on:
      - postgres

  redis:
    <<: *common-keys-selab
    container_name: redis_prod
    image: redis:latest
    entrypoint: redis-server --appendonly yes --maxmemory 512mb --maxmemory-policy allkeys-lru
    volumes:
      - ${DATA_DIR}/redis:/data

  celery:
    <<: *common-keys-selab
    container_name: celery_prod
    build:
      context: $BACKEND_DIR
      dockerfile: Dockerfile.prod
    command: celery -A ypovoli worker -l ERROR
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/overlay2:/var/lib/docker/overlay2
    depends_on:
      - backend
      - redis

  frontend:
    <<: *common-keys-selab
    container_name: frontend_prod
    build:
      context: $FRONTEND_DIR
      dockerfile: Dockerfile.prod
    depends_on:
      - backend

  docs:
    <<: *common-keys-selab
    container_name: docs_prod
    build:
      context: $DOCS_DIR
      dockerfile: Dockerfile.prod
