version: "3.9"

############################# NETWORKS

networks:
  test_selab_network:
    name: test_selab_network
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.91.0/24

############################# EXTENSIONS

x-common-keys-selab: &common-keys-selab
  networks:
    - test_selab_network
  security_opt:
    - no-new-privileges:true
  restart: unless-stopped
  environment:
    TZ: $TZ
    PUID: $PUID
    PGID: $PGID
  env_file:
    - .env

############################# SERVICES

services:
  test_nginx:
    <<: *common-keys-selab
    image: nginx:latest
    container_name: test_nginx
    expose:
      - 80
      - 443
      - 8080
    volumes:
      - ${DATA_DIR}/nginx/nginx.test.conf:/etc/nginx/nginx.conf:ro
      - ${SSL_DIR}:/etc/nginx/ssl:ro
    depends_on:
      - test_backend
      - test_frontend

  test_backend:
    <<: *common-keys-selab
    container_name: test_backend
    build:
      context: $BACKEND_DIR
      dockerfile: Dockerfile
    command: /bin/bash -c "./setup.sh && python manage.py runsslserver 192.168.91.2:8080"
    expose:
      - 8080
    volumes:
      - $BACKEND_DIR:/code

  test_celery:
    <<: *common-keys-selab
    container_name: test_celery
    build:
      context: $BACKEND_DIR
      dockerfile: Dockerfile
    command: celery -A ypovoli worker -l DEBUG
    volumes:
      - $BACKEND_DIR:/code
    depends_on:
      - test_backend
      - test_redis

  test_frontend:
    <<: *common-keys-selab
    container_name: test_frontend
    build:
      context: $FRONTEND_DIR
      dockerfile: Dockerfile.dev
    command: bash -c "npm install && npm run host"
    expose:
      - 5173
    volumes:
      - $FRONTEND_DIR:/app
    depends_on:
      - test_backend

  test_redis:
    <<: *common-keys-selab
    container_name: test_redis
    image: redis:latest
    networks:
      test_selab_network:
        ipv4_address: 192.168.91.10
    expose:
      - 6379
    entrypoint: redis-server --appendonly yes --maxmemory 512mb --maxmemory-policy allkeys-lru
    volumes:
      - ${DATA_DIR}/redis:/data

  test_cypress:
    <<: *common-keys-selab
    container_name: test_cypress
    image: cypress/included:cypress-12.17.3-node-18.16.0-chrome-114.0.5735.133-1-ff-114.0.2-edge-114.0.1823.51-1
    restart: "no"
    working_dir: /e2e
    volumes:
      - ${FRONTEND_DIR}:/e2e
    extra_hosts:
      - "host.docker.internal:host-gateway"
