version: "3.9"

############################# NETWORKS

networks:
  test_selab_network:
    name: test_selab_network
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.92.0/24

############################# EXTENSIONS

x-common-keys-selab_test: &common-keys-selab_test
  networks:
    - test_selab_network
  security_opt:
    - no-new-privileges:true
  restart: "no"
  environment:
    TZ: $TZ
    PUID: $PUID
    PGID: $PGID
  env_file:
    - .env
  dns:
    - 1.1.1.1
    - 4.4.4.4
    - 8.8.8.8

############################# SERVICES

services:
  nginx:
    <<: *common-keys-selab_test
    image: nginx:latest
    container_name: nginx
    volumes:
      - ${DATA_DIR}/nginx/nginx.test.conf:/etc/nginx/nginx.conf:ro
      - ${SSL_DIR}:/etc/nginx/ssl:ro
    depends_on:
      - backend
      - frontend

  backend:
    <<: *common-keys-selab_test
    container_name: backend
    build:
      context: $BACKEND_DIR
      dockerfile: Dockerfile
    command: sh -c "./setup.sh && python manage.py runsslserver 0.0.0.0:8000"
    volumes:
      - $BACKEND_DIR:/code

  celery:
    <<: *common-keys-selab_test
    container_name: celery
    build:
      context: $BACKEND_DIR
      dockerfile: Dockerfile
    command: sh -c "poetry install && celery -A ypovoli worker -l DEBUG"
    volumes:
      - $BACKEND_DIR:/code
    depends_on:
      - backend
      - redis

  frontend:
    <<: *common-keys-selab_test
    container_name: frontend
    build:
      context: $FRONTEND_DIR
      dockerfile: Dockerfile.dev
    command: sh -c "npm install && npm run host"
    volumes:
      - $FRONTEND_DIR:/app
    depends_on:
      - backend

  redis:
    <<: *common-keys-selab_test
    container_name: redis
    image: redis:latest
    entrypoint: redis-server --appendonly yes --maxmemory 512mb --maxmemory-policy allkeys-lru
    volumes:
      - ${DATA_DIR}/redis:/data

  cypress:
    <<: *common-keys-selab_test
    container_name: cypress
    image: cypress/included:cypress-12.17.3-node-18.16.0-chrome-114.0.5735.133-1-ff-114.0.2-edge-114.0.1823.51-1
    working_dir: /e2e
    volumes:
      - ${FRONTEND_DIR}:/e2e
