<script setup lang="ts">
import Calendar from 'primevue/calendar';
import BaseLayout from '@/components/layout/base/BaseLayout.vue';
import FileUpload from 'primevue/fileupload';
import Title from '@/components/layout/Title.vue';
import ErrorMessage from '@/components/forms/ErrorMessage.vue';
import InputText from 'primevue/inputtext';
import Editor from '@/components/forms/Editor.vue';
import Button from 'primevue/button';
import InputNumber from 'primevue/inputnumber';
import InputSwitch from 'primevue/inputswitch';
import { reactive, computed } from 'vue';
import { useRouter, useRoute } from 'vue-router';
import { useI18n } from 'vue-i18n';
import { Project } from '@/types/Project';
import { useProject } from '@/composables/services/project.service';
import { required, helpers } from '@vuelidate/validators';
import { useVuelidate } from '@vuelidate/core';
import { useCourses } from '@/composables/services/course.service';

/* Composable injections */
const { t } = useI18n();
const { push } = useRouter();
const { params } = useRoute();

/* Service injection */
const { createProject } = useProject();
const { course, getCourseByID } = useCourses();

/* Form content */
const form = reactive({
    name: '',
    description: '',
    startDate: new Date(),
    deadline: new Date(),
    groupSize: 1,
    maxScore: 10,
    visibility: true,
    scoreVisibility: false,
    dockerScript: null,
    submissionStructure: null,
});

// Define validation rules for each form field
const rules = computed(() => {
    return {
        name: { required: helpers.withMessage(t('validations.required'), required) },
        startDate: { required: helpers.withMessage(t('validations.required'), required) },
        deadline: {
            required: helpers.withMessage(t('validations.required'), required),
            minDate: helpers.withMessage(t('validations.deadline'), (value: Date) => value > form.startDate),
        },
        groupSize: { required: helpers.withMessage(t('validations.required'), required) },
        maxScore: { required: helpers.withMessage(t('validations.required'), required) },
    };
});

// Function to handle the file upload of a docker script
const onDockerScriptUpload = (event: any): void => {
    form.dockerScript = event.files[0];
};

// Function to handle the file upload of a zip file containing the submission structure
const onZipStructureUpload = (event: any): void => {
    form.submissionStructure = event.files[0];
};

// useVuelidate function to perform form validation
const v$ = useVuelidate(rules, form);

/**
 * Function to submit the project form.
 */
async function submitProject(): Promise<void> {
    // Validate the form
    const validated = await v$.value.$validate();

    // Get the course object from the course ID
    await getCourseByID(params.courseId as string);

    // Only submit the form if the validation was successful
    if (validated && course.value !== null) {
        // Pass the project data to the service
        await createProject(
            new Project(
                '', // ID not needed for creation, will be generated by the backend
                form.name,
                form.description,
                form.visibility,
                false, // Default not archived
                false, // Default the groups are not locked
                form.startDate,
                form.deadline,
                form.maxScore,
                form.scoreVisibility,
                form.groupSize,
                course.value,
                form.submissionStructure,
            ),
            params.courseId as string,
        );

        // Redirect to the dashboard overview
        await push({ name: 'dashboard' });
    }
}
</script>

<template>
    <BaseLayout>
        <!-- Create project heading -->
        <Title class="mb-6">
            {{ t('views.projects.create') }}
        </Title>

        <!-- Project form -->
        <form @submit.prevent="submitProject">
            <div class="grid">
                <div class="col-12 lg:col-6">
                    <div class="grid formgrid">
                        <!-- Project name -->
                        <div class="field col-12">
                            <label for="projectName">
                                {{ t('views.projects.name') }}
                            </label>
                            <InputText id="projectName" class="w-full" v-model="form.name" />
                            <ErrorMessage :field="v$.name" />
                        </div>
                    </div>

                    <div class="grid">
                        <!-- Project description -->
                        <div class="field col">
                            <label for="projectDescription">
                                {{ t('views.projects.description') }}
                            </label>
                            <Editor id="projectDescription" class="w-full" v-model="form.description" />
                        </div>
                    </div>

                    <div class="grid">
                        <!-- Start date of the project -->
                        <div class="field col">
                            <label for="projectStartDate">{{ t('views.projects.start_date') }}</label>
                            <Calendar
                                id="projectStartDate"
                                class="w-full"
                                v-model="form.startDate"
                                dateFormat="dd-mm-yy"
                                :min-date="new Date()"
                                showIcon
                            />
                            <ErrorMessage :field="v$.startDate" />
                        </div>

                        <!-- Deadline of the project -->
                        <div class="field col">
                            <label for="projectDeadline">{{ t('views.projects.deadline') }}</label>
                            <Calendar
                                id="projectDeadline"
                                class="w-full"
                                v-model="form.deadline"
                                dateFormat="dd-mm-yy"
                                :min-date="form.startDate"
                                showTime
                                hourFormat="24"
                                showIcon
                            />
                            <ErrorMessage :field="v$.deadline" />
                        </div>
                    </div>

                    <div class="grid align-items-end">
                        <!-- Group size for the project -->
                        <div class="field col">
                            <label for="groupSize">
                                {{ t('views.projects.group_size') }}
                            </label>
                            <InputNumber id="groupSize" class="w-full" v-model="form.groupSize" :min="1" />
                            <ErrorMessage :field="v$.groupSize" />
                        </div>

                        <!-- Max score for the project -->
                        <div class="field col">
                            <label for="maxScore">{{ t('views.projects.max_score') }}</label>
                            <InputNumber id="maxScore" class="w-full" v-model="form.maxScore" :min="1" />
                            <ErrorMessage :field="v$.maxScore" />
                        </div>
                    </div>

                    <!-- Visibility of the project -->
                    <div class="grid">
                        <div class="flex align-items-center field-checkbox col-12">
                            <InputSwitch id="visibility" v-model="form.visibility" />
                            <label for="visibility">{{ t('views.projects.visibility') }}</label>
                        </div>
                    </div>

                    <!-- Score visibility of the project -->
                    <div class="grid">
                        <div class="flex align-items-center field-checkbox col-12">
                            <InputSwitch id="scoreVisibility" v-model="form.scoreVisibility" />
                            <label for="scoreVisibility">{{ t('views.projects.scoreVisibility') }}</label>
                        </div>
                    </div>

                    <!-- Submit button -->
                    <Button
                        :label="t('views.projects.create')"
                        type="submit"
                        icon="pi pi-check"
                        iconPos="right"
                        rounded
                    />
                </div>

                <div class="col-12 lg:col-6">
                    <!-- Upload field for docker script -->
                    <div class="field col">
                        <label for="dockerScript">
                            {{ t('views.projects.dockerUpload') }}
                        </label>
                        <FileUpload
                            input="dockerScript"
                            mode="basic"
                            accept=".sh"
                            :multiple="false"
                            title="hellaur"
                            @select="onDockerScriptUpload"
                        />
                    </div>

                    <!-- Upload field for a zip file that contains the submission structure -->
                    <div class="field col">
                        <label for="submissionStructure">
                            {{ t('views.projects.submissionStructure') }}
                        </label>
                        <FileUpload
                            id="submissionStructure"
                            mode="basic"
                            accept=".zip"
                            :multiple="false"
                            @select="onZipStructureUpload"
                        />
                    </div>
                </div>
            </div>
        </form>
    </BaseLayout>
</template>

<style scoped></style>
@/types/Project
