FROM node:18.17.1-alpine3.17 as build-stage
WORKDIR /docs
COPY package*.json ./
RUN npm install
COPY ./ .
RUN npm run build

FROM nginx:alpine-slim as production-stage
EXPOSE 3000
RUN mkdir /docs
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build-stage /docs/.vitepress/dist /docs
