name: backend-linting

on:
  pull_request:
    branches: [main, development]
  workflow_dispatch:

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Add permission to remove contents of previous action script
        run: echo ${{ secrets.SUDO }} | sudo -S chown -R $USER:$USER /home/selab2/actions-runner/_work/UGent-7/
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install --directory=./backend
      - name: Execute linting checks
        run: flake8 --config ./backend/.flake8 ./backend
