name: backend-linting

on:
  pull_request:
    branches: [main, development]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          cd backend
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
      - name: Execute linting checks
        run: cd backend; poetry run flake8 --config .flake8
