name: Deploy
on:
  push:
    branches:
      - deployment

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd test
            git checkout deployment
            docker-compose -f production.yml down
            git pull
            docker-compose -f production.yml build --no-cache
            docker-compose -f production.yml up -d
