name: tests

on:
  pull_request:
    branches: [main, development]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        run: ./test.sh -c
